const ProjectConfig = {
    TaskMasterGridsize: "xl:col-span-2 xl:row-span-2",
    "Online-Library-applicationGridsize": "xl:col-span-3 xl:row-span-2 ",
    MultiTimerGridsize: "xl:col-span-3 xl:row-span-2",
    "CSB-and-Networking-Final-ProjectGridsize": "xl:col-span-2 xl:row-span-4 ",
    "4k-youtube-downloader-with-UIGridsize": "xl:col-span-2 xl:row-span-2 ",
    AlphaKeysGridsize: "xl:col-span-6 xl:row-span-2 ",
    "Python-Socket-Chat-AppGridsize": "xl:col-span-6 xl:row-span-2 ",
    GeatGridsize: "xl:col-span-2 xl:row-span-2 ",
    "small-web-projectsGridsize": "xl:col-span-2 xl:row-span-2 ",

    TaskMaster: 'bg-[url("/Image/projects_photo/TaskmasterMockup.png")]',
    MultiTimer: 'bg-[url("/Image/projects_photo/MuliTimer.png")]',
    AlphaKeys: 'bg-[url("/Image/projects_photo/s0kpiseth.github.io_AlphaKeys_.png")]',
    "CSB-and-Networking-Final-Project": 'bg-[url("/Image/projects_photo/Paper.png")]',
    "4k-youtube-downloader-with-UI": 'bg-[url("/Image/projects_photo/Home_tab_dark.png")]',
    "Online-Library-application": 'bg-[url("/Image/projects_photo/library.png")]',
    Geat: 'bg-[url("/Image/projects_photo/Geat.png")]',
    "Python-Socket-Chat-App": 'bg-[url("/Image/projects_photo/Python-Socket-Chat-App.png")] max-[1024px]:bg-contain',
    "small-web-projects": 'bg-[url("/Image/projects_photo/small-web-projects.png")]',

    'TaskMasterLang': ["React", "Html","Css","JavaScript"],
    'MultiTimerLang': ["Python"],
    'AlphaKeysLang': ["React", "Html","Css","JavaScript"],
    "CSB-and-Networking-Final-ProjectLang": ["Python"],
    "4k-youtube-downloader-with-UILang": ["Python", "SQLite"],
    "Online-Library-applicationLang": ["Java", "SQLite"],
    'GeatLang': ["React", "Html","Css","JavaScript"],
    "Python-Socket-Chat-AppLang":["Python"],
    "small-web-projectsLang":["Html","Css","JavaScript"],
  };
export default ProjectConfig;